image: node:22

stages:
    - deploy

# variables:
#     NODE_ENV: prod
#     PNPM_HOME: /root/.local/share/pnpm
#     PATH: "$PNPM_HOME:$PATH"

deploy_production:
    stage: deploy
    before_script:
        - corepack enable
        - pnpm install --frozen-lockfile
        - pnpm run build
    script:
        # Build + deploy ke Cloudflare Workers lewat adapter OpenNext
        - pnpm run deploy
    only:
        - main # sesuaikan dengan nama branch produksi kamu
    environment:
        name: prod
    tags:
        - docker-cloud
